[application]
host = "0.0.0.0"
port = 8080
body_limit = "10MB"
request_timeout_seconds = 15
graceful_shutdown = false

[my-custom-section]
custom_key = "custom_value"
env_var = "${USER:default_value}"